from __future__ import annotations

WINDOWS_AUDIO_SAMPLE_RATE = 48000
WINDOWS_AUDIO_CHANNELS = 2
WINDOWS_AUDIO_BIT_DEPTH = 16
WINDOWS_AUDIO_DTYPE = "int16"

ASR_SAMPLE_RATE = 16000
ASR_CHANNELS = 1
ASR_DTYPE = "float32"

__all__ = [
    "ASR_CHANNELS",
    "ASR_DTYPE",
    "ASR_SAMPLE_RATE",
    "WINDOWS_AUDIO_BIT_DEPTH",
    "WINDOWS_AUDIO_CHANNELS",
    "WINDOWS_AUDIO_DTYPE",
    "WINDOWS_AUDIO_SAMPLE_RATE",
]
